# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gzkeyboard',
                'doc_host': 'https://AI4Basics.github.io',
                'git_url': 'https://github.com/AI4Basics/gzkeyboard',
                'lib_path': 'gzkeyboard'},
  'syms': {'gzkeyboard.core': {'gzkeyboard.core.foo': ('core.html#foo', 'gzkeyboard/core.py')}}}
