"""Keyman-inspired context-driven rules for natural Ge'ez input with immediate character output"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_composition.ipynb.

# %% auto 0
__all__ = ['CompositionAction', 'CompositionRule', 'SeparatorRule', 'DoubleStrikeRule', 'LabiovelarRule', 'FifthOrderRule',
           'VowelRule', 'DigramSecondKeyRule', 'ConsonantRule', 'PunctuationRule', 'LoneVowelRule', 'ContextEngine',
           'simulate_typing']

# %% ../nbs/01_composition.ipynb 3
from typing import Dict, List, Optional, Tuple, Set
from dataclasses import dataclass, field
from abc import ABC, abstractmethod
from .core import CharacterStore, VowelOrder

# %% ../nbs/01_composition.ipynb 5
@dataclass
class CompositionAction:
    """Result of processing a single keystroke through the composition engine.
    
    Attributes:
        output: Character(s) to output after backspacing
        backspaces: Number of backspaces to send first (to replace previous char)
        new_context: The new 'last character' for next rule matching
    """
    output: str = ""
    backspaces: int = 0
    new_context: str = ""

# %% ../nbs/01_composition.ipynb 7
class CompositionRule(ABC):
    """Base class for a context + key -> action rule."""
    
    @abstractmethod
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        """Check if this rule applies to the given context and key."""
        ...
    
    @abstractmethod
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        """Apply this rule and return the action."""
        ...
    
    @property
    @abstractmethod
    def priority(self) -> int:
        """Rule priority. Higher = checked first."""
        ...

# %% ../nbs/01_composition.ipynb 8
class SeparatorRule(CompositionRule):
    """Apostrophe breaks composition: any_geez + "'" -> same char + dead state.
    
    The apostrophe acts as a separator between syllables, preventing
    the next keystroke from modifying the current character.
    """
    
    @property
    def priority(self) -> int: return 100
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        return key == "'" and context != "" and store.is_geez_char(context)
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        # No output change, just clear context so next key starts fresh
        return CompositionAction(output="", backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 9
class DoubleStrikeRule(CompositionRule):
    """Double-strike cycles through alternate forms: e.g., ስ + 's' -> ሥ.
    
    When the context is a sadis character and the user presses the same
    consonant key again, cycle to the alternate form.
    """
    
    @property
    def priority(self) -> int: return 90
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if not context or not store.is_geez_char(context):
            return False
        # Context must be a sadis character
        order = store.get_vowel_order_of(context)
        if order != 5:  # Must be sadis (6th order)
            return False
        # The key must be the same consonant key that produced this character
        ctx_key = store.get_key_for_sadis(context)
        if ctx_key != key:
            # Also check alternates - if context is an alternate sadis,
            # check if pressing the original key would cycle it
            alt = store.get_alternate(context)
            if alt is not None:
                alt_key = store.get_key_for_sadis(alt)
                if alt_key == key:
                    return True
            return False
        # Must have an alternate
        return store.get_alternate(context) is not None
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        alt = store.get_alternate(context)
        return CompositionAction(output=alt, backspaces=1, new_context=alt)

# %% ../nbs/01_composition.ipynb 10
class LabiovelarRule(CompositionRule):
    """Labiovelar composition: e.g., ኩ + 'a' -> ኳ (2nd order + vowel -> labiovelar).
    
    When the context is a character from a family that has a labiovelar variant,
    and the character is in 2nd order (kaeb/u), a vowel key produces the
    labiovelar form instead.
    
    Also handles: sadis + 'w' + vowel via two-step process:
    - First step (handled by VowelRule): ክ + 'u' -> ኩ  
    - Second step (this rule): ኩ + 'a' -> ኳ
    """
    
    # Maps base consonant key -> labiovelar family key
    LABIOVELAR_MAP = {
        'h': 'hw', 'x': 'hw',
        'k': 'kw', 'kh': 'kw',
        'q': 'qw', 'qha': 'qw',
        'g': 'gw',
    }
    
    @property
    def priority(self) -> int: return 80
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if not context or not store.is_geez_char(context):
            return False
        # Context must be kaeb (2nd order, index 1) of a family with labiovelars
        order = store.get_vowel_order_of(context)
        if order != 1:  # Must be kaeb (u form)
            return False
        base_key = store.find_family_for_character(context)
        if base_key not in self.LABIOVELAR_MAP:
            return False
        # Key must be a vowel (but not 'u' — that would just stay as kaeb)
        return key in ('a', 'i', 'e', 'o')
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        base_key = store.find_family_for_character(context)
        lv_key = self.LABIOVELAR_MAP[base_key]
        # Map vowel key to vowel order
        vowel_order = VowelOrder.from_latin_key(key)
        if vowel_order is None:
            return CompositionAction(output=key, backspaces=0, new_context="")
        lv_family = store.get_family(lv_key)
        char = lv_family.get_character_by_index(vowel_order.index)
        if char is not None:
            return CompositionAction(output=char, backspaces=1, new_context=char)
        # Fallback: no labiovelar at this order
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 11
class FifthOrderRule(CompositionRule):
    """5th order shortcut: 3rd order + 'e' -> 5th order (e.g., ሂ + 'e' -> ሄ).
    
    Like GFF Keyman: typing the 3rd order (salis/i) form followed by 'e'
    produces the 5th order (hams/e) form. This is a common typing shortcut
    since 'ie' is a natural way to type the 5th order sound.
    """
    
    @property
    def priority(self) -> int: return 70
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if not context or key != 'e' or not store.is_geez_char(context):
            return False
        # Context must be 3rd order (salis, index 2)
        order = store.get_vowel_order_of(context)
        return order == 2
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        # Replace 3rd order with 5th order in the same family
        char = store.get_same_family_at_order(context, 4)  # index 4 = hams (5th order)
        if char is not None:
            return CompositionAction(output=char, backspaces=1, new_context=char)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 12
class VowelRule(CompositionRule):
    """Vowel modifies a sadis character: e.g., ህ + 'a' -> ሃ.
    
    When the context is a sadis (6th order) character and the user presses
    a vowel key, replace with the appropriate vowel order form.
    """
    
    VOWEL_KEYS = {'a', 'u', 'i', 'e', 'o'}
    
    @property
    def priority(self) -> int: return 60
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if not context or key not in self.VOWEL_KEYS or not store.is_geez_char(context):
            return False
        # Context must be sadis (6th order, index 5)
        order = store.get_vowel_order_of(context)
        return order == 5
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        vowel_order = VowelOrder.from_latin_key(key)
        if vowel_order is None:
            return CompositionAction(output=key, backspaces=0, new_context="")
        char = store.get_same_family_at_order(context, vowel_order.index)
        if char is not None:
            return CompositionAction(output=char, backspaces=1, new_context=char)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 13
class DigramSecondKeyRule(CompositionRule):
    """Digram composition: e.g., ስ + 'h' -> ሽ (s + h -> sh family).
    
    When the context is a sadis character and the next key forms a digram
    (two-letter consonant), replace with the digram family's sadis.
    """
    
    # Maps (context_sadis_char_family, second_key) -> digram_base_key
    # We store by family base_key for clarity
    DIGRAM_MAP = {
        ('s', 'h'):  'sh',   # s + h -> sh
        ('z', 'h'):  'zh',   # z + h -> zh
        ('t', 's'):  'ts',   # t + s -> ts
        ('n', 'y'):  'ny',   # n + y -> ny
    }
    
    @property
    def priority(self) -> int: return 50
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if not context or not store.is_geez_char(context):
            return False
        # Context must be sadis
        order = store.get_vowel_order_of(context)
        if order != 5:
            return False
        base_key = store.get_key_for_sadis(context)
        if base_key is None:
            return False
        return (base_key, key) in self.DIGRAM_MAP
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        base_key = store.get_key_for_sadis(context)
        digram_key = self.DIGRAM_MAP[(base_key, key)]
        sadis = store.get_sadis_for_key(digram_key)
        if sadis is not None:
            return CompositionAction(output=sadis, backspaces=1, new_context=sadis)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 14
class ConsonantRule(CompositionRule):
    """Bare consonant key -> sadis form: e.g., 'h' -> ህ.
    
    When a consonant key is pressed (with no composable context),
    immediately output its sadis (6th order) form.
    
    Special case: 'c' is treated as 'ch' (outputs ች directly).
    """
    
    # Maps single keys to base_key in the store
    CONSONANT_MAP = {
        'h': 'h', 'l': 'l', 'm': 'm', 'r': 'r',
        's': 's', 'q': 'q', 'b': 'b', 'v': 'v',
        't': 't', 'c': 'ch',  # 'c' alone = ch
        'n': 'n', 'k': 'k',
        'w': 'w', 'z': 'z', 'y': 'y',
        'd': 'd', 'j': 'j', 'g': 'g',
        'f': 'f', 'p': 'p',
        'x': 'x',
    }
    
    @property
    def priority(self) -> int: return 30
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        return key in self.CONSONANT_MAP
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        base_key = self.CONSONANT_MAP[key]
        sadis = store.get_sadis_for_key(base_key)
        if sadis is not None:
            return CompositionAction(output=sadis, backspaces=0, new_context=sadis)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 15
class PunctuationRule(CompositionRule):
    """Circular punctuation cycling: ':' -> '፡' -> '።' -> ':' -> ...
    
    Ge'ez uses unique punctuation marks. This rule cycles through
    punctuation variants on repeated keypresses.
    """
    
    PUNCT_CYCLES = {
        ':': '፡',     # colon -> Ge'ez word separator
        '፡': '።',    # word separator -> full stop
        '።': ':',     # full stop -> back to colon
        ';': '፤',     # semicolon -> Ge'ez semicolon
        '፤': ';',     # back to semicolon
        ',': '፣',     # comma -> Ge'ez comma
        '፣': ',',     # back to comma
        '?': '፧',     # question -> Ge'ez question mark
        '፧': '?',     # back to question
    }
    
    @property
    def priority(self) -> int: return 25
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        # Matches when key is a punctuation trigger
        if key in (':', ';', ',', '?'):
            return True
        # Also matches when context is a Ge'ez punctuation and same-category key is pressed
        if context in self.PUNCT_CYCLES and key == self._get_base_key(context):
            return True
        return False
    
    def _get_base_key(self, char: str) -> str:
        """Get the base Latin key for a Ge'ez punctuation character."""
        if char in ('፡', '።'): return ':'
        if char == '፤': return ';'
        if char == '፣': return ','
        if char == '፧': return '?'
        return char
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        # If context is a Ge'ez punctuation that can cycle
        if context in self.PUNCT_CYCLES:
            next_char = self.PUNCT_CYCLES[context]
            return CompositionAction(output=next_char, backspaces=1, new_context=next_char)
        # First press of a punctuation key
        if key in self.PUNCT_CYCLES:
            next_char = self.PUNCT_CYCLES[key]
            return CompositionAction(output=next_char, backspaces=0, new_context=next_char)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 16
class LoneVowelRule(CompositionRule):
    """Lone vowel when no consonant context: 'e' -> እ, 'a' -> አ, etc.
    
    When the context is empty (no previous Ge'ez character), vowel keys
    produce lone vowel characters from the vowel family.
    """
    
    # Maps vowel keys to vowel family indices
    VOWEL_KEY_TO_INDEX = {
        'e': 5,  # እ (sadis) - default lone vowel for 'e'
        'u': 1,  # ኡ (kaeb)
        'i': 2,  # ኢ (salis)
        'a': 3,  # ኣ (rabe)  
        'o': 6,  # ኦ (sabe)
    }
    
    @property
    def priority(self) -> int: return 20
    
    def matches(self, context: str, key: str, store: CharacterStore) -> bool:
        if key not in self.VOWEL_KEY_TO_INDEX:
            return False
        # Only match when context is empty or non-composable
        if context and store.is_geez_char(context):
            return False
        return True
    
    def apply(self, context: str, key: str, store: CharacterStore) -> CompositionAction:
        index = self.VOWEL_KEY_TO_INDEX[key]
        vowel_family = store.get_family('_v')
        if vowel_family:
            char = vowel_family.get_character_by_index(index)
            if char is not None:
                return CompositionAction(output=char, backspaces=0, new_context=char)
        return CompositionAction(output=key, backspaces=0, new_context="")

# %% ../nbs/01_composition.ipynb 18
class ContextEngine:
    """Context-driven composition engine (replaces SyllableComposer).
    
    Processes keystrokes using Keyman-style context rules. Each keystroke
    produces immediate output; subsequent keystrokes may replace the previous
    character via backspace.
    
    Args:
        store: CharacterStore with all character families loaded
    """
    
    def __init__(self, store: CharacterStore):
        self.store = store
        self.context = ""   # Last output character
        self.rules: List[CompositionRule] = []
        self._build_rules()
    
    def _build_rules(self):
        """Build and sort rules by priority (highest first)."""
        self.rules = [
            SeparatorRule(),
            DoubleStrikeRule(),
            LabiovelarRule(),
            FifthOrderRule(),
            VowelRule(),
            DigramSecondKeyRule(),
            ConsonantRule(),
            PunctuationRule(),
            LoneVowelRule(),
        ]
        self.rules.sort(key=lambda r: r.priority, reverse=True)
    
    def process_key(self, key: str) -> CompositionAction:
        """Process a single keystroke. Returns action (output + backspaces).
        
        Args:
            key: The key pressed (single character)
            
        Returns:
            CompositionAction with output, backspaces, and new context
        """
        # Try rules in priority order
        for rule in self.rules:
            if rule.matches(self.context, key, self.store):
                action = rule.apply(self.context, key, self.store)
                self.context = action.new_context
                return action
        
        # No rule matched - pass key through unchanged
        self.context = ""
        return CompositionAction(output=key, backspaces=0, new_context="")
    
    def reset(self):
        """Reset engine state (clear context)."""
        self.context = ""

# %% ../nbs/01_composition.ipynb 23
def simulate_typing(engine: ContextEngine, text: str, show_steps: bool = True) -> str:
    """Simulate typing a sequence and show step-by-step composition.
    
    Returns the final composed text (what would appear on screen).
    """
    engine.reset()
    screen = []  # Simulates what's on screen
    
    if show_steps:
        print(f"Typing: '{text}'")
        print("-" * 50)
    
    for key in text:
        action = engine.process_key(key)
        
        # Apply backspaces
        for _ in range(action.backspaces):
            if screen:
                screen.pop()
        
        # Apply output
        if action.output:
            screen.append(action.output)
        
        if show_steps:
            screen_str = ''.join(screen)
            print(f"  '{key}' -> bs={action.backspaces}, out='{action.output}' | screen: '{screen_str}'")
    
    result = ''.join(screen)
    if show_steps:
        print(f"Result: '{result}'")
        print()
    return result
