"""User-configurable settings, custom mappings, and preferences for the GzKeyboard"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_configuration.ipynb.

# %% auto 0
__all__ = ['CustomMapping']

# %% ../nbs/03_configuration.ipynb 3
from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass, asdict, field
from pathlib import Path
import json
import os
from datetime import datetime

from .core import CharacterStore, CharacterFamily
from .composition import CompositionStrategy
from .system import InputMode

# %% ../nbs/03_configuration.ipynb 4
@dataclass
class CustomMapping:
    """Represents a custom character or word mapping."""
    input_sequence: str
    output: str
    priority: int = 0
    description: str = ""
    enabled: bool = True
