"""User-configurable settings, custom mappings, and preferences for the GzKeyboard"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_configuration.ipynb.

# %% auto 0
__all__ = ['CustomMapping', 'LanguageConfig', 'get_tigrinya_config', 'get_amharic_config']

# %% ../nbs/03_configuration.ipynb 3
from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass, field
from pathlib import Path
import json
import os

from .core import CharacterStore, CharacterFamily

# %% ../nbs/03_configuration.ipynb 4
@dataclass
class CustomMapping:
    """Represents a custom character or word mapping."""
    input_sequence: str
    output: str
    priority: int = 0
    description: str = ""
    enabled: bool = True

@dataclass
class LanguageConfig:
    """Language-specific configuration for Tigrinya or Amharic.
    
    Encapsulates differences between language variants:
    - Extra character families specific to the language
    - Double-strike alternate mappings
    - Custom composition rules
    """
    name: str                                           # "tigrinya" or "amharic"
    extra_families: List[CharacterFamily] = field(default_factory=list)
    alternate_map: Dict[str, str] = field(default_factory=dict)
    custom_mappings: List[CustomMapping] = field(default_factory=list)


def get_tigrinya_config() -> LanguageConfig:
    """Get Tigrinya-specific language configuration."""
    return LanguageConfig(
        name="tigrinya",
        alternate_map={
            # Tigrinya uses both ጸ and ፀ
            'ጽ': 'ፅ',
            'ፅ': 'ጽ',
        }
    )

def get_amharic_config() -> LanguageConfig:
    """Get Amharic-specific language configuration."""
    return LanguageConfig(
        name="amharic",
        alternate_map={
            # Amharic typically uses ጸ but not ፀ
            'ሥ': 'ስ',
            'ስ': 'ሥ',
        }
    )
