"""Character stores and syllable composition for Geez keyboards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['VowelOrder', 'CharacterFamily', 'CharacterStore', 'AmharicCharacterStore', 'MappingsConfig', 'explore_family',
           'show_composition_examples', 'save_character_store', 'load_character_store']

# %% ../nbs/00_core.ipynb 3
from typing import ClassVar, Dict, List, Optional, Set, Tuple
from enum import Enum
from dataclasses import dataclass
import json
from pathlib import Path

# %% ../nbs/00_core.ipynb 5
class VowelOrder(Enum):
    """Traditional Geez vowel order system.
    
    Latin key mapping follows Keyman/GFF convention:
    - 'e' → 1st order (ግዕዝ) — the most common form
    - 5th order (ኃምስ) has no direct key — accessed via 'ie' shortcut (3rd + 'e')
    - 6th order (ሳድስ) is the default bare consonant output
    """
    GEEZ  = (0, "ግዕዝ", "e", "ä")      # Base form — typed with 'e'
    KAEB  = (1, "ካዕብ", "u", "u")      # Second order
    SALIS = (2, "ሣልስ", "i", "i")      # Third order  
    RABE  = (3, "ራብዕ", "a", "a")      # Fourth order
    HAMS  = (4, "ኃምስ",  "", "e")      # Fifth order — accessed via 'ie' (FifthOrderRule)
    SADES = (5, "ሳድስ",  "", "ə")      # Sixth order — default (bare consonant)
    SABE  = (6, "ሳብዕ", "o", "o")      # Seventh order
    
    def __init__(self, index, geez_name, latin_key, ipa):
        self.index     = index
        self.geez_name = geez_name
        self.latin_key = latin_key
        self.ipa       = ipa
    
    @classmethod
    def from_latin_key(cls, key: str) -> Optional['VowelOrder']:
        """Get vowel order from Latin key."""
        for vowel in cls:
            if vowel.latin_key == key:
                return vowel
        return None
    
    @classmethod
    def from_index(cls, index: int) -> Optional['VowelOrder']:
        """Get vowel order from index."""
        for vowel in cls:
            if vowel.index == index:
                return vowel
        return None

# %% ../nbs/00_core.ipynb 8
@dataclass
class CharacterFamily:
    """
    Represents a family of Geez characters with vowel variations.
    
    Characters list must have exactly 7 entries (one per vowel order).
    Entries may be None for families that lack certain forms (e.g., labiovelars).
    """
    base_key     : str                      # Latin key (e.g., 'h', 's', 'l')
    characters   : List[Optional[str]]      # 7 characters in vowel order (None if form doesn't exist)
    name         : str                      # Human readable name
    unicode_range: Tuple[int, int]          # Unicode start and end points
    
    def __post_init__(self):
        if len(self.characters) != 7:
            raise ValueError(f"Character family must have exactly 7 entries, got {len(self.characters)}")
    
    def get_character(self, vowel_order: VowelOrder) -> Optional[str]:
        """Get character for specific vowel order."""
        return self.characters[vowel_order.index]
    
    def get_character_by_index(self, index: int) -> Optional[str]:
        """Get character by vowel index (0-6)."""
        if 0 <= index < 7:
            return self.characters[index]
        return None
    
    def get_character_by_latin_key(self, vowel_key: str) -> Optional[str]:
        """Get character by Latin vowel key."""
        vowel_order = VowelOrder.from_latin_key(vowel_key)
        if vowel_order:
            return self.get_character(vowel_order)
        return None
    
    @property
    def sadis(self) -> Optional[str]:
        """Get the 6th order (sadis) form - the default output form."""
        return self.characters[5]
    
    @property
    def valid_characters(self) -> List[str]:
        """Get list of non-None characters in this family."""
        return [c for c in self.characters if c is not None]

# %% ../nbs/00_core.ipynb 11
class CharacterStore:
    """Manages character families and provides lookup functionality.
    
    Supports Keyman-style parallel store operations:
    - Forward lookup: base_key + vowel → character
    - Reverse lookup: character → family + vowel order
    - Parallel index: given a character, find same family at different vowel order
    """
    
    def __init__(self):
        self.families             : Dict[str, CharacterFamily] = {}
        self._character_to_family : Dict[str, str] = {}    # char → base_key
        self._character_to_index  : Dict[str, int] = {}     # char → vowel index
        self._sadis_to_key        : Dict[str, str] = {}           # sadis char → base_key
        self.alternates           : Dict[str, str] = {}              # sadis char → alternate sadis char
        self._initialize_default_families()
        self._initialize_alternates()
    
    def _initialize_default_families(self):
        """Initialize with standard Geez character families."""
        default_families = [
            # --- Standard consonants ---
            CharacterFamily('h',   ['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ'], 'ሀ family (h)',    (0x1200, 0x1206)),
            CharacterFamily('l',   ['ለ', 'ሉ', 'ሊ', 'ላ', 'ሌ', 'ል', 'ሎ'], 'ለ family (l)',    (0x1208, 0x120E)),
            CharacterFamily('hh',  ['ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሕ', 'ሖ'], 'ሐ family (hh)',   (0x1210, 0x1216)),
            CharacterFamily('m',   ['መ', 'ሙ', 'ሚ', 'ማ', 'ሜ', 'ም', 'ሞ'], 'መ family (m)',    (0x1218, 0x121E)),
            CharacterFamily('ss',  ['ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሥ', 'ሦ'], 'ሠ family (ss)',   (0x1220, 0x1226)),
            CharacterFamily('r',   ['ረ', 'ሩ', 'ሪ', 'ራ', 'ሬ', 'ር', 'ሮ'], 'ረ family (r)',    (0x1228, 0x122E)),
            CharacterFamily('s',   ['ሰ', 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ', 'ሶ'], 'ሰ family (s)',    (0x1230, 0x1236)),
            CharacterFamily('sh',  ['ሸ', 'ሹ', 'ሺ', 'ሻ', 'ሼ', 'ሽ', 'ሾ'], 'ሸ family (sh)',   (0x1238, 0x123E)),
            CharacterFamily('q',   ['ቀ', 'ቁ', 'ቂ', 'ቃ', 'ቄ', 'ቅ', 'ቆ'], 'ቀ family (q)',    (0x1240, 0x1246)),
            CharacterFamily('qh',  ['ቐ', 'ቑ', 'ቒ', 'ቓ', 'ቔ', 'ቕ', 'ቖ'], 'ቐ family (qh)',   (0x1250, 0x1256)),
            CharacterFamily('b',   ['በ', 'ቡ', 'ቢ', 'ባ', 'ቤ', 'ብ', 'ቦ'], 'በ family (b)',    (0x1260, 0x1266)),
            CharacterFamily('v',   ['ቨ', 'ቩ', 'ቪ', 'ቫ', 'ቬ', 'ቭ', 'ቮ'], 'ቨ family (v)',    (0x1268, 0x126E)),
            CharacterFamily('t',   ['ተ', 'ቱ', 'ቲ', 'ታ', 'ቴ', 'ት', 'ቶ'], 'ተ family (t)',    (0x1270, 0x1276)),
            CharacterFamily('ch',  ['ቸ', 'ቹ', 'ቺ', 'ቻ', 'ቼ', 'ች', 'ቾ'], 'ቸ family (ch)',   (0x1278, 0x127E)),
            CharacterFamily('x',   ['ኀ', 'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ'], 'ኀ family (x)',    (0x1280, 0x1286)),
            CharacterFamily('n',   ['ነ', 'ኑ', 'ኒ', 'ና', 'ኔ', 'ን', 'ኖ'], 'ነ family (n)',    (0x1290, 0x1296)),
            CharacterFamily('gn',  ['ኘ', 'ኙ', 'ኚ', 'ኛ', 'ኜ', 'ኝ', 'ኞ'], 'ኘ family (gn)',   (0x1298, 0x129E)),
            CharacterFamily('_v',  ['አ', 'ኡ', 'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ'], 'Vowel family',    (0x12A0, 0x12A6)),
            CharacterFamily('k',   ['ከ', 'ኩ', 'ኪ', 'ካ', 'ኬ', 'ክ', 'ኮ'], 'ከ family (k)',    (0x12A8, 0x12AE)),
            CharacterFamily('kh',  ['ኸ', 'ኹ', 'ኺ', 'ኻ', 'ኼ', 'ኽ', 'ኾ'], 'ኸ family (kh)',   (0x12B8, 0x12BE)),
            CharacterFamily('w',   ['ወ', 'ዉ', 'ዊ', 'ዋ', 'ዌ', 'ው', 'ዎ'], 'ወ family (w)',    (0x12C8, 0x12CE)),
            CharacterFamily('_a',  ['ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ'], 'ዐ family (ayin)', (0x12D0, 0x12D6)),
            CharacterFamily('z',   ['ዘ', 'ዙ', 'ዚ', 'ዛ', 'ዜ', 'ዝ', 'ዞ'], 'ዘ family (z)',    (0x12D8, 0x12DE)),
            CharacterFamily('zh',  ['ዠ', 'ዡ', 'ዢ', 'ዣ', 'ዤ', 'ዥ', 'ዦ'], 'ዠ family (zh)',   (0x12E0, 0x12E6)),
            CharacterFamily('y',   ['የ', 'ዩ', 'ዪ', 'ያ', 'ዬ', 'ይ', 'ዮ'], 'የ family (y)',    (0x12E8, 0x12EE)),
            CharacterFamily('d',   ['ደ', 'ዱ', 'ዲ', 'ዳ', 'ዴ', 'ድ', 'ዶ'], 'ደ family (d)',    (0x12F0, 0x12F6)),
            CharacterFamily('j',   ['ጀ', 'ጁ', 'ጂ', 'ጃ', 'ጄ', 'ጅ', 'ጆ'], 'ጀ family (j)',    (0x1300, 0x1306)),
            CharacterFamily('g',   ['ገ', 'ጉ', 'ጊ', 'ጋ', 'ጌ', 'ግ', 'ጎ'], 'ገ family (g)',    (0x1308, 0x130E)),
            CharacterFamily('tt',  ['ጠ', 'ጡ', 'ጢ', 'ጣ', 'ጤ', 'ጥ', 'ጦ'], 'ጠ family (tt)',   (0x1320, 0x1326)),
            CharacterFamily('chh', ['ጨ', 'ጩ', 'ጪ', 'ጫ', 'ጬ', 'ጭ', 'ጮ'], 'ጨ family (chh)',  (0x1328, 0x132E)),
            CharacterFamily('pp',  ['ጰ', 'ጱ', 'ጲ', 'ጳ', 'ጴ', 'ጵ', 'ጶ'], 'ጰ family (pp)',   (0x1330, 0x1336)),
            CharacterFamily('ts',  ['ጸ', 'ጹ', 'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ'], 'ጸ family (ts)',   (0x1338, 0x133E)),
            CharacterFamily('tss', ['ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ'], 'ፀ family (tss)',  (0x1340, 0x1346)),
            CharacterFamily('f',   ['ፈ', 'ፉ', 'ፊ', 'ፋ', 'ፌ', 'ፍ', 'ፎ'], 'ፈ family (f)',    (0x1348, 0x134E)),
            CharacterFamily('p',   ['ፐ', 'ፑ', 'ፒ', 'ፓ', 'ፔ', 'ፕ', 'ፖ'], 'ፐ family (p)',    (0x1350, 0x1356)),
            
            # --- Labiovelar families (5 forms only) ---
            CharacterFamily('hw',  ['ኈ', None, 'ኊ', 'ኋ', 'ኌ', 'ኍ', None], 'ሀ labiovelar (hw)', (0x1288, 0x128D)),
            CharacterFamily('kw',  ['ኰ', None, 'ኲ', 'ኳ', 'ኴ', 'ኵ', None], 'ከ labiovelar (kw)', (0x12B0, 0x12B5)),
            CharacterFamily('qw',  ['ቈ', None, 'ቊ', 'ቋ', 'ቌ', 'ቍ', None], 'ቀ labiovelar (qw)', (0x1248, 0x124D)),
            CharacterFamily('gw',  ['ጐ', None, 'ጒ', 'ጓ', 'ጔ', 'ጕ', None], 'ገ labiovelar (gw)', (0x1310, 0x1315)),
        ]
        
        for family in default_families:
            self.add_family(family)
    
    def _initialize_alternates(self):
        """Initialize double-strike alternate mappings."""
        self.alternates = {
            'ስ': 'ሥ',   # s → ss (ሰ → ሠ)
            'ሥ': 'ስ',   # ss → s (cycle back)
            'ህ': 'ኅ',   # h → x (ሀ → ኀ)
            'ኅ': 'ሕ',   # x → hh (ኀ → ሐ)
            'ሕ': 'ህ',   # hh → h (cycle back)
            'አ': 'ዓ',   # vowel-a → ayin-a
            'ዓ': 'ዐ',   # ayin-a → ayin-geez
            'ዐ': 'አ',   # ayin-geez → vowel-a (cycle back)
        }
    
    def add_family(self, family: CharacterFamily):
        """Add a character family to the store."""
        self.families[family.base_key] = family
        for i, char in enumerate(family.characters):
            if char is not None:
                self._character_to_family[char] = family.base_key
                self._character_to_index[char] = i
        if family.sadis is not None:
            self._sadis_to_key[family.sadis] = family.base_key
    
    def _remove_family(self, base_key: str):
        """Remove a character family and its reverse-lookup entries.
        
        Used by mode-specific subclasses to exclude families not present
        in a particular language (e.g. Amharic vs Tigrinya).
        """
        family = self.families.pop(base_key, None)
        if family:
            for char in family.characters:
                if char is not None:
                    self._character_to_family.pop(char, None)
                    self._character_to_index.pop(char, None)
            if family.sadis is not None:
                self._sadis_to_key.pop(family.sadis, None)
    
    def get_family(self, base_key: str) -> Optional[CharacterFamily]:
        return self.families.get(base_key)
    
    def get_character(self, base_key: str, vowel_key: str) -> Optional[str]:
        family = self.get_family(base_key)
        if family:
            return family.get_character_by_latin_key(vowel_key)
        return None
    
    def find_family_for_character(self, character: str) -> Optional[str]:
        return self._character_to_family.get(character)
    
    def get_all_base_keys(self) -> List[str]:
        return list(self.families.keys())
    
    def has_family(self, base_key: str) -> bool:
        return base_key in self.families
    
    def get_vowel_order_of(self, char: str) -> Optional[int]:
        return self._character_to_index.get(char)
    
    def get_same_family_at_order(self, char: str, target_order: int) -> Optional[str]:
        base_key = self._character_to_family.get(char)
        if base_key is None:
            return None
        return self.families[base_key].get_character_by_index(target_order)
    
    def get_sadis_for_key(self, base_key: str) -> Optional[str]:
        family = self.get_family(base_key)
        return family.sadis if family else None
    
    def get_key_for_sadis(self, sadis_char: str) -> Optional[str]:
        return self._sadis_to_key.get(sadis_char)
    
    def get_alternate(self, char: str) -> Optional[str]:
        return self.alternates.get(char)
    
    def is_geez_char(self, char: str) -> bool:
        return char in self._character_to_family

# %% ../nbs/00_core.ipynb 12
class AmharicCharacterStore(CharacterStore):
    """CharacterStore for Amharic — starts from the full Tigrinya store and
    removes families that are not part of the standard Amharic alphabet.

    To adjust which families are excluded, edit AMHARIC_EXCLUDED.
    """

    # Families present in Tigrinya but not standard Amharic
    AMHARIC_EXCLUDED = {
        'qh',   # ቐ — Tigrinya ejective, absent from Amharic
        'tss',  # ፀ — Tigrinya emphatic sibilant, absent from Amharic
    }

    def __init__(self):
        super().__init__()
        for key in self.AMHARIC_EXCLUDED:
            self._remove_family(key)

# %% ../nbs/00_core.ipynb 13
@dataclass
class MappingsConfig:
    """User-configurable key sequence → character family mappings.

    `sequence_to_family` maps every typing sequence to its target family base_key.
    Single-char entries (e.g. ``'h': 'h'``) drive ``ConsonantRule``.
    Multi-char entries (e.g. ``'sh': 'sh'``, ``'tss': 'tss'``) drive
    ``DigramSecondKeyRule``.

    Use `default()` for factory settings and `save()`/`load()` for persistence
    to ``~/.gzkeyboard/mappings.json``.
    """

    sequence_to_family: Dict[str, str]

    CONFIG_DIR : ClassVar[Path] = Path.home() / '.gzkeyboard'
    CONFIG_PATH: ClassVar[Path] = Path.home() / '.gzkeyboard' / 'mappings.json'

    @classmethod
    def default(cls) -> 'MappingsConfig':
        """Return the factory-default key sequence mappings."""
        return cls(sequence_to_family={
            # Single-key consonants (drive ConsonantRule)
            'h': 'h',  'l': 'l',  'm': 'm',  'r': 'r',
            's': 's',  'q': 'q',  'b': 'b',  'v': 'v',
            't': 't',  'n': 'n',  'k': 'k',  'w': 'w',
            'z': 'z',  'y': 'y',  'd': 'd',  'j': 'j',
            'g': 'g',  'f': 'f',  'p': 'p',  'x': 'x',
            # Multi-key sequences (drive DigramSecondKeyRule)
            'sh':  'sh',  'zh':  'zh',  'ts':  'ts',  'tss': 'tss',
            'gn':  'gn',  'ch':  'ch',  'hh':  'hh',  'qh':  'qh',
            'kh':  'kh',
            'tt':  'tt',  'chh': 'chh', 'pp':  'pp',
            'hw':  'hw',  'kw':  'kw',  'qw':  'qw',  'gw':  'gw',
        })

    def get_consonant_map(self) -> Dict[str, str]:
        """Return ``{key: family_base_key}`` for all single-character sequences."""
        return {seq: fam for seq, fam in self.sequence_to_family.items() if len(seq) == 1}

    def get_digram_map(self) -> Dict[Tuple[str, str], str]:
        """Derive the digram rule map from multi-char sequences.

        For a sequence ``'tss'``, splits as ``('ts', 's') → 'tss'``.
        For ``'sh'``, splits as ``('s', 'h') → 'sh'``.
        The prefix (all chars except last) is the context key in the rule.
        """
        digram: Dict[Tuple[str, str], str] = {}
        for seq, fam in self.sequence_to_family.items():
            if len(seq) > 1:
                prefix, last = seq[:-1], seq[-1]
                digram[(prefix, last)] = fam
        return digram

    def get_pending_keys(self) -> Set[str]:
        """Return keys that produce no output (first char of digrams with no solo family).

        E.g. ``'c'`` starts ``'ch'``/``'chh'`` but has no single-char entry → pending.
        """
        single_keys  = {seq       for seq in self.sequence_to_family if len(seq) == 1}
        multi_starts = {seq[0]    for seq in self.sequence_to_family if len(seq) > 1}
        return multi_starts - single_keys

    def save(self, path: Optional[Path] = None):
        """Save mappings to JSON (default: ``~/.gzkeyboard/mappings.json``)."""
        target = path or self.CONFIG_PATH
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, 'w', encoding='utf-8') as f:
            json.dump(self.sequence_to_family, f, ensure_ascii=False, indent=2)

    @classmethod
    def load(cls, path: Optional[Path] = None) -> 'MappingsConfig':
        """Load mappings from JSON, falling back to defaults if file not found."""
        target = path or cls.CONFIG_PATH
        if not target.exists():
            return cls.default()
        with open(target, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return cls(sequence_to_family=data)

# %% ../nbs/00_core.ipynb 17
def explore_family(store: CharacterStore, base_key: str):
    """Display detailed information about a character family."""
    family = store.get_family(base_key)
    if not family:
        print(f"No family found for key '{base_key}'")
        return
    
    print(f"\n{family.name}")
    print("=" * len(family.name))
    print(f"Base key: {family.base_key}")
    print(f"Unicode range: U+{family.unicode_range[0]:04X} - U+{family.unicode_range[1]:04X}")
    print("\nCharacters:")
    
    for i, char in enumerate(family.characters):
        vowel = VowelOrder.from_index(i)
        print(f"  {vowel.geez_name:4} ({vowel.latin_key:2}): {char} (U+{ord(char):04X})")

def show_composition_examples(store: CharacterStore, examples: List[Tuple[str, str]]):
    """Show examples of character composition."""
    print("\nComposition Examples:")
    print("====================")
    print(f"{'Input':10} {'Output':8} {'Unicode':10} {'Family':15}")
    print("-" * 50)
    
    for base_key, vowel_key in examples:
        char = store.get_character(base_key, vowel_key)
        if char:
            input_str = f"{base_key}{vowel_key}"
            unicode_str = f"U+{ord(char):04X}"
            family_name = store.get_family(base_key).name.split('(')[0].strip()
            print(f"{input_str:10} {char:8} {unicode_str:10} {family_name:15}")
        else:
            print(f"{base_key}{vowel_key:10} {'N/A':8} {'N/A':10} {'N/A':15}")

# %% ../nbs/00_core.ipynb 22
def save_character_store(store: CharacterStore, filepath: Path):
    """Save character store to JSON file."""
    data = {
        'families': {
            key: {
                'base_key': family.base_key,
                'characters': family.characters,
                'name': family.name,
                'unicode_range': family.unicode_range
            }
            for key, family in store.families.items()
        }
    }
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def load_character_store(filepath: Path) -> CharacterStore:
    """Load character store from JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    store = CharacterStore()
    store.families.clear()  # Remove default families
    store._character_to_family.clear()
    
    for key, family_data in data['families'].items():
        family = CharacterFamily(
            base_key=family_data['base_key'],
            characters=family_data['characters'],
            name=family_data['name'],
            unicode_range=tuple(family_data['unicode_range'])
        )
        store.add_family(family)
    
    return store
