"""Main application integration and command-line interface for the new GzKeyboard system"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_main.ipynb.

# %% auto 0
__all__ = ['interactive_mode', 'main']

# %% ../nbs/04_main.ipynb 2
__all__ = ['main']

import argparse
import sys
import time
from pathlib import Path

from .core import CharacterStore
from .composition import ContextEngine, simulate_typing
from .system import SystemInputHandler, InputMode, KeyboardConfig, start_keyboard, stop_keyboard

# %% ../nbs/04_main.ipynb 3
def interactive_mode(mode: str = "tigrinya"):
    """Run an interactive terminal session for typing Ge'ez.
    
    Works without keyboard hooks — reads single characters from stdin
    and shows the composed output. Useful for testing on WSL2 or
    environments without /dev/input access.
    """
    import sys, tty, termios
    
    store = CharacterStore()
    engine = ContextEngine(store)
    
    print(f"GzKeyboard Interactive Terminal ({mode} mode)")
    print("=" * 50)
    print("Type characters to compose Ge'ez. Press Ctrl+C to exit.")
    print("Press Backspace to delete, Enter for newline.")
    print()
    
    screen = []  # What's been committed to screen
    
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    
    try:
        tty.setraw(fd)
        
        while True:
            ch = sys.stdin.read(1)
            
            # Ctrl+C to exit
            if ch == '\x03':
                break
            
            # Enter
            if ch in ('\r', '\n'):
                sys.stdout.write('\r\n')
                sys.stdout.flush()
                screen.clear()
                engine.reset()
                continue
            
            # Backspace
            if ch in ('\x7f', '\x08'):
                if screen:
                    screen.pop()
                    engine.reset()
                    # Clear line and rewrite
                    sys.stdout.write('\r\033[K')
                    sys.stdout.write(''.join(screen))
                    sys.stdout.flush()
                continue
            
            # Process through engine
            if ch.isalpha() or ch in "':.;,?":
                action = engine.process_key(ch)
                
                # Apply backspaces
                for _ in range(action.backspaces):
                    if screen:
                        screen.pop()
                
                # Apply output
                if action.output:
                    screen.append(action.output)
                
                # Redraw line
                sys.stdout.write('\r\033[K')
                sys.stdout.write(''.join(screen))
                sys.stdout.flush()
            else:
                # Non-composable: pass through and reset context
                engine.reset()
                screen.append(ch)
                sys.stdout.write('\r\033[K')
                sys.stdout.write(''.join(screen))
                sys.stdout.flush()
    
    except KeyboardInterrupt:
        pass
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        print("\n\nFinal output:", ''.join(screen))
        print("Goodbye!")

def main():
    """Main command-line entry point for GzKeyboard."""
    parser = argparse.ArgumentParser(
        description="GzKeyboard - Context-driven Ge'ez keyboard for Tigrinya and Amharic"
    )
    
    parser.add_argument(
        "--mode", 
        choices=["tigrinya", "amharic", "latin"],
        default="tigrinya",
        help="Input mode (default: tigrinya)"
    )
    
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run composition tests with sample words"
    )
    
    parser.add_argument(
        "--interactive", "-i",
        action="store_true",
        help="Run interactive terminal mode (works on WSL2, no root needed)"
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode with detailed logging"
    )
    
    args = parser.parse_args()
    
    if args.test:
        print("GzKeyboard Interactive Tests (Context-Driven Engine)")
        print("=" * 55)
        
        store = CharacterStore()
        engine = ContextEngine(store)
        
        test_words = ['selam', 'halo', 'geez', 'shalom', "g'iz"]
        for word in test_words:
            simulate_typing(engine, word)
        
        print("Tests completed!")
        return
    
    if args.interactive:
        interactive_mode(args.mode)
        return
    
    # Start the actual keyboard system
    print(f"Starting GzKeyboard in {args.mode} mode...")
    
    handler = start_keyboard(args.mode, args.debug)
    
    if handler.keyboard_hook_active:
        try:
            print("Start typing! Press Ctrl+C to exit.")
            while True:
                time.sleep(0.1)
        except KeyboardInterrupt:
            print("\nGzKeyboard stopped. Goodbye!")
            stop_keyboard(handler)
    else:
        print("Failed to start keyboard hooks.")
        print("Try running with --interactive (-i) for terminal mode (no root needed)")
        print("Or use --test to verify the composition engine")

# %% ../nbs/04_main.ipynb 4
if __name__ == "__main__":
    main()
