"""Main application integration and command-line interface for the new GzKeyboard system"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_main.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../nbs/04_main.ipynb 2
__all__ = ['main']

import argparse
import sys
import time
from pathlib import Path

from .core import CharacterStore
from .composition import ContextEngine, simulate_typing
from .system import SystemInputHandler, InputMode, KeyboardConfig, start_keyboard, stop_keyboard

# %% ../nbs/04_main.ipynb 3
def main():
    """Main command-line entry point for GzKeyboard."""
    parser = argparse.ArgumentParser(
        description="GzKeyboard - Context-driven Ge'ez keyboard for Tigrinya and Amharic"
    )
    
    parser.add_argument(
        "--mode", 
        choices=["tigrinya", "amharic", "latin"],
        default="tigrinya",
        help="Input mode (default: tigrinya)"
    )
    
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run interactive composition tests"
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode with detailed logging"
    )
    
    args = parser.parse_args()
    
    if args.test:
        print("GzKeyboard Interactive Tests (Context-Driven Engine)")
        print("=" * 55)
        
        store = CharacterStore()
        engine = ContextEngine(store)
        
        test_words = ['selam', 'halo', 'geez', 'shalom', "g'iz"]
        for word in test_words:
            simulate_typing(engine, word)
        
        print("Tests completed!")
        return
    
    # Start the actual keyboard system
    print(f"Starting GzKeyboard in {args.mode} mode...")
    
    handler = start_keyboard(args.mode, args.debug)
    
    if handler.keyboard_hook_active:
        try:
            print("Start typing! Press Ctrl+C to exit.")
            while True:
                time.sleep(0.1)
        except KeyboardInterrupt:
            print("\nGzKeyboard stopped. Goodbye!")
            stop_keyboard(handler)
    else:
        print("Failed to start keyboard hooks.")
        print("Try running with --test to verify the composition engine works")
