"""System-wide keyboard hooks and integration with the improved composition engine"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_system_integration.ipynb.

# %% auto 0
__all__ = ['InputMode', 'KeyboardConfig', 'HotkeyManager', 'StatusIndicator', 'SystemInputHandler', 'create_default_config',
           'start_keyboard', 'stop_keyboard', 'main']

# %% ../nbs/02_system_integration.ipynb 3
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass
from enum import Enum
import sys
import os
import argparse
import time
from pathlib import Path

from .core import CharacterStore
from .composition import ContextEngine, CompositionAction

# %% ../nbs/02_system_integration.ipynb 5
class InputMode(Enum):
    """Defines the input modes available in the Geez keyboard."""
    TIGRINYA = "tigrinya"
    AMHARIC = "amharic"
    LATIN = "latin"  # For regular typing without conversion

@dataclass
class KeyboardConfig:
    """Configuration for the Geez keyboard input method."""
    default_mode: InputMode = InputMode.TIGRINYA
    
    # Hotkey configuration
    toggle_hotkey: str = "ctrl+space"
    tigrinya_hotkey: str = "alt+t"
    amharic_hotkey: str = "alt+a"
    latin_hotkey: str = "alt+l"
    cancel_hotkey: str = "escape"
    
    # Advanced settings
    show_notifications: bool = True
    debug_mode: bool = False

# %% ../nbs/02_system_integration.ipynb 7
class HotkeyManager:
    """Manages hotkeys for controlling the Geez keyboard."""
    
    def __init__(self, config: KeyboardConfig):
        self.config = config
        self.callbacks: Dict[str, Callable] = {}
        self.registered_hotkeys: List[str] = []
    
    def register_callback(self, action: str, callback: Callable):
        """Register a callback for a specific action."""
        self.callbacks[action] = callback
    
    def setup_hotkeys(self):
        """Set up system hotkeys using the keyboard library."""
        try:
            import keyboard
            
            # Define hotkey mappings
            hotkey_map = {
                self.config.toggle_hotkey: 'toggle_input',
                self.config.tigrinya_hotkey: 'switch_to_tigrinya',
                self.config.amharic_hotkey: 'switch_to_amharic',
                self.config.latin_hotkey: 'switch_to_latin',
                self.config.cancel_hotkey: 'cancel_buffer'
            }
            
            # Register hotkeys
            for hotkey, action in hotkey_map.items():
                if action in self.callbacks:
                    keyboard.add_hotkey(hotkey, self.callbacks[action])
                    self.registered_hotkeys.append(hotkey)
                    if self.config.debug_mode:
                        print(f"Registered hotkey: {hotkey} → {action}")
            
            return True
            
        except ImportError:
            print("Keyboard library not available. Hotkeys disabled.")
            return False
    
    def cleanup(self):
        """Clean up registered hotkeys."""
        try:
            import keyboard
            for hotkey in self.registered_hotkeys:
                keyboard.remove_hotkey(hotkey)
            self.registered_hotkeys.clear()
        except ImportError:
            pass

# %% ../nbs/02_system_integration.ipynb 9
class StatusIndicator:
    """A status indicator for the Geez keyboard."""
    
    def __init__(self, config: KeyboardConfig):
        self.config = config
        self.visible = False
        self.current_mode = config.default_mode
        self.active = True
    
    def show_status(self, message: str, duration: float = 2.0):
        """Show a status message."""
        if self.config.show_notifications:
            print(f"[GzKeyboard] {message}")
            self.visible = True
    
    def update_mode(self, mode: InputMode):
        """Update the current input mode."""
        self.current_mode = mode
        self.show_status(f"Switched to {mode.value} mode")
    
    def toggle_active(self):
        """Toggle active/inactive state."""
        self.active = not self.active
        status = "activated" if self.active else "deactivated"
        self.show_status(f"GzKeyboard {status}")
    
    def show_buffer_state(self, buffer: str, suggestions: List[str] = None):
        """Show current buffer state for debugging."""
        if self.config.debug_mode and buffer:
            msg = f"Buffer: '{buffer}'"
            if suggestions:
                msg += f" | Suggestions: {suggestions[:3]}"
            print(f"[DEBUG] {msg}")
    
    def hide(self):
        """Hide the status indicator."""
        self.visible = False

# %% ../nbs/02_system_integration.ipynb 11
class SystemInputHandler:
    """Handles system-wide keyboard input for the Geez keyboard.
    
    Uses the context-driven ContextEngine for immediate character output
    with backspace+replace behavior.
    """
    
    def __init__(self, config: Optional[KeyboardConfig] = None):
        """Initialize the input handler with configuration."""
        self.config = config or KeyboardConfig()
        
        # Initialize components
        self.character_store = CharacterStore()
        self.engine = ContextEngine(self.character_store)
        self.status = StatusIndicator(self.config)
        self.hotkey_manager = HotkeyManager(self.config)
        
        # State
        self.current_mode = self.config.default_mode
        self.active = True
        self.keyboard_hook_active = False
        
        # Setup hotkey callbacks
        self._setup_hotkey_callbacks()
    
    def _setup_hotkey_callbacks(self):
        """Set up hotkey callback functions."""
        self.hotkey_manager.register_callback('toggle_input', self.toggle_active)
        self.hotkey_manager.register_callback('switch_to_tigrinya', lambda: self.switch_mode(InputMode.TIGRINYA))
        self.hotkey_manager.register_callback('switch_to_amharic', lambda: self.switch_mode(InputMode.AMHARIC))
        self.hotkey_manager.register_callback('switch_to_latin', lambda: self.switch_mode(InputMode.LATIN))
        self.hotkey_manager.register_callback('cancel_buffer', self.reset_engine)
    
    def switch_mode(self, mode: InputMode):
        """Switch to a different input mode."""
        self.current_mode = mode
        self.status.update_mode(mode)
        self.engine.reset()
    
    def toggle_active(self):
        """Toggle the keyboard active/inactive state."""
        self.active = not self.active
        self.status.toggle_active()
        if self.active:
            self.engine.reset()
    
    def reset_engine(self):
        """Reset the composition engine context."""
        self.engine.reset()
        self.status.show_status("Context cleared")
    
    def setup_keyboard_hook(self):
        """Set up system-wide keyboard hook with suppress=True for intercept+replace."""
        try:
            import keyboard
            
            def on_key_event(event):
                """Handle keyboard events."""
                # Only process key down events
                if event.event_type != keyboard.KEY_DOWN:
                    return True
                
                # Skip if not active or in Latin mode
                if not self.active or self.current_mode == InputMode.LATIN:
                    return True
                
                key = event.name
                
                # Process composable keys through context engine
                if len(key) == 1 and (key.isalpha() or key in "':.;,?"):
                    action = self.engine.process_key(key)
                    
                    if self.config.debug_mode:
                        print(f"[DEBUG] key='{key}' -> bs={action.backspaces}, out='{action.output}', ctx='{action.new_context}'")
                    
                    # Execute the action
                    if action.backspaces > 0:
                        for _ in range(action.backspaces):
                            keyboard.send('backspace')
                    
                    if action.output:
                        keyboard.write(action.output)
                    
                    return False  # Suppress original keystroke
                
                # Non-composable key resets context
                self.engine.reset()
                return True  # Let it through
            
            # suppress=True to intercept keys before they reach the application
            keyboard.hook(on_key_event, suppress=True)
            self.keyboard_hook_active = True
            
            # Set up hotkeys
            hotkeys_setup = self.hotkey_manager.setup_hotkeys()
            
            if self.config.debug_mode:
                print(f"Keyboard hook active: {self.keyboard_hook_active}")
                print(f"Hotkeys setup: {hotkeys_setup}")
            
            return True
            
        except ImportError:
            self.status.show_status("Keyboard library not available. Please install required dependencies.")
            return False
        except Exception as e:
            self.status.show_status(f"Error setting up keyboard hook: {e}")
            return False
    
    def cleanup(self):
        """Clean up resources."""
        self.hotkey_manager.cleanup()
        self.keyboard_hook_active = False
    
    def get_status(self) -> dict:
        """Get current status information."""
        return {
            'active': self.active,
            'current_mode': self.current_mode.value,
            'keyboard_hook_active': self.keyboard_hook_active,
            'current_context': self.engine.context,
            'registered_hotkeys': len(self.hotkey_manager.registered_hotkeys),
        }

# %% ../nbs/02_system_integration.ipynb 13
def create_default_config(mode: str = "tigrinya", 
                         debug: bool = False) -> KeyboardConfig:
    """Create a default configuration."""
    try:
        input_mode = InputMode(mode.lower())
    except ValueError:
        print(f"Invalid mode: {mode}. Using Tigrinya.")
        input_mode = InputMode.TIGRINYA
    
    return KeyboardConfig(
        default_mode=input_mode,
        debug_mode=debug
    )

def start_keyboard(mode: str = "tigrinya", 
                  debug: bool = False) -> SystemInputHandler:
    """Start the Geez keyboard with specified configuration."""
    config = create_default_config(mode, debug)
    handler = SystemInputHandler(config)
    
    success = handler.setup_keyboard_hook()
    
    if success:
        handler.status.show_status(
            f"GzKeyboard started in {mode} mode (context-driven engine)"
        )
        
        print("\nHotkeys:")
        print(f"  {config.toggle_hotkey}: Toggle keyboard on/off")
        print(f"  {config.tigrinya_hotkey}: Switch to Tigrinya")
        print(f"  {config.amharic_hotkey}: Switch to Amharic")
        print(f"  {config.latin_hotkey}: Switch to Latin")
        print(f"  {config.cancel_hotkey}: Reset context")
        print("\nPress Ctrl+C to exit")
    else:
        print("Failed to start keyboard. Check dependencies and permissions.")
    
    return handler

def stop_keyboard(handler: SystemInputHandler):
    """Stop the keyboard and clean up resources."""
    handler.cleanup()
    handler.status.show_status("GzKeyboard stopped")

# %% ../nbs/02_system_integration.ipynb 15
def main():
    """Command-line entry point for the Geez Keyboard."""
    parser = argparse.ArgumentParser(
        description="GzKeyboard - Context-driven Geez keyboard for Tigrinya and Amharic",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m gzkeyboard.system                    # Start with default settings
  python -m gzkeyboard.system --mode amharic     # Start in Amharic mode
  python -m gzkeyboard.system --test             # Run interactive tests
  python -m gzkeyboard.system --debug            # Enable debug mode
"""
    )
    
    parser.add_argument(
        "--mode", 
        choices=["tigrinya", "amharic", "latin"],
        default="tigrinya",
        help="Input mode (default: tigrinya)"
    )
    
    parser.add_argument(
        "--test",
        action="store_true",
        help="Run interactive composition tests"
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug mode with detailed logging"
    )
    
    args = parser.parse_args()
    
    if args.test:
        from gzkeyboard.composition import simulate_typing
        
        print("GzKeyboard Interactive Tests (Context-Driven Engine)")
        print("=" * 55)
        
        store = CharacterStore()
        engine = ContextEngine(store)
        
        test_words = ['selam', 'halo', 'geez', 'shalom']
        for word in test_words:
            simulate_typing(engine, word)
        
        print("Tests completed!")
        return
    
    # Start the keyboard
    handler = start_keyboard(args.mode, args.debug)
    
    if handler.keyboard_hook_active:
        try:
            while True:
                time.sleep(0.1)
        except KeyboardInterrupt:
            print("\nShutting down GzKeyboard...")
            stop_keyboard(handler)
    else:
        print("Failed to start keyboard hooks. Exiting.")

if __name__ == "__main__":
    main()
